// Generated by https://quicktype.io

export interface IProducts {
    errors: any[];
    status: number;
    data:   Products[];
    estado: null;
}

export interface Products {
    productoId:  number;
    descripcion: string;
    amount:      number;
    avalaible:   number;
}
