// Generated by https://quicktype.io

export interface IHistorical {
    errors: any[];
    status: number;
    data: DatosHistorical[];
    estado: null;
}

export interface DatosHistorical {
    userName: string;
    dateLogin: string;
}
