// Generated by https://quicktype.io

export interface IReserva {
    errors: any[];
    status: number;
    data:   Reservas[];
    estado: null;
}

export interface Reservas {
    userName:    string;
    description: string;
}
