// Generated by https://quicktype.io

export interface IUsers {
    errors: any[];
    status: number;
    data: Users[];
    estado: null;
}

export interface Users {
    userName: string;
    nombreCompleto: null;
    edad: null;
    genero: null;
    nacionalidad: null;
    rol: string;
}
